# Tarea 2 - Numpy

> lea detalladamente el ejercicio antes de responder los ejercicios

# Carlos flores y Fabricio zeballos

1. Crear los siguientes arregos de numpy
> * Crear un array con 10 elementos 
> * Crear un array con 5 numeros decimales
> * crear un array de 20 elementos con solo  numeros pares

In [1]:
import numpy as np

In [ ]:
array=np.arange(10)
print(array) # primer ejercicio array de 10 elementos

#array con cinco numeros decimal
array2=np.array([1.1,2.2,3.3,4.4,5.5])
print(array2)

#array con 20 pares

array3=np.arange(2,42,2)

print(array3)



2. Cual es la forma correcta de crear un Array
> * A) np.createArray([1,2,3,4,5])
> * B) np.object([1,2,3,4,5])
> * C) np.array([1,2,3,4,5])

In [ ]:
crear_arraycorecto=np.array([1,2,3,4,5])
print(crear_arraycorecto)

3. Cual es la forma correcta de saber el numero de dimensiones de un array
> * arr.ndim()
> * arr.dim()   
> * arr.ndim
> * arr.dim

In [26]:
#ejercicio 3
op=np.array([1,2,3])

print(op.ndim) # la respuesta es arr.ndim 

1


4. Cual es la sintaxis correcta para imprimir el primer item de un array
> * print(arr,1)
> * print(arr[1])
> * print(arr[0]) 

In [27]:
#el correcto es el tercero

op=np.array([1,2,3])

print(op[0])

1


5. Cual es la sintaxis correcta para imprimir el numero 8 del vector
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
> * print(arr(1,2))
> * print(arr(7,2))
> * print(arr(3,0))

In [31]:
#la correcta es el 1

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1,2]) #seria el uno pero hay una falla que tiene que ser con [] y no con ()

8


6. Cual es la sintaxis correcta para imprimir [3, 4, 5] del array 
arr = np.array([1,2,3,4,5,6,7])
> * print(arr[3:6])
> * print(arr[2:5])
> * print(arr[2:6])
> * print(arr[2:4])

In [33]:
arr = np.array([1,2,3,4,5,6,7])

print(arr[2:5]) # la correcta es la dos

[3 4 5]


7. Crear un vector con valores dentro del rango 10 a 49

In [35]:
vector=np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8. Invertir el vector creado en la pregunta anterior

In [36]:
vector=np.arange(10,50)
print(vector[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]



9. Crear una matriz 3x3 con valores de 0 a 8

In [37]:
matriz=np.arange(9)
matriz3x3=matriz.reshape(3,3)

print(matriz3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


10. Crear una matriz identidad de 6x6

In [38]:
matriz_identidad=np.identity(6)
print(matriz_identidad)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


11. Encontrar los valores que no son ceros del arreglo [1,2,4,2,4,0,1,0,0,0,12,4,5,6,7,0]

In [41]:
arreglo=np.array([1,2,4,2,4,0,1,0,0,0,12,4,5,6,7,0])

indices_no_ceros=np.nonzero(arreglo)

result=arreglo[indices_no_ceros]
print(result)

[ 1  2  4  2  4  1 12  4  5  6  7]


12. Crear una matriz con valores al azar con forma 3x3x3

In [42]:
matriz_aleatorio=np.random.rand(3,3,3)
print(matriz_aleatorio)

[[[0.85427002 0.57056919 0.76389071]
  [0.86997445 0.9220805  0.49375965]
  [0.47365694 0.27072191 0.27838556]]

 [[0.37977745 0.53067383 0.21045482]
  [0.66416724 0.95225762 0.53175433]
  [0.96399683 0.05009977 0.14767035]]

 [[0.84420952 0.89698803 0.55828407]
  [0.79739325 0.50550178 0.91367124]
  [0.25577323 0.11172642 0.76982358]]]


13. Crear una matriz de 10x10 con 1's en los bordes y cualquier valor en el interior(investigar)

In [ ]:
matriz= np.random.rand(10,10)

matriz[0,:]=1
matriz[-1,:]=1
matriz[:,0]=1
matriz[:,-1]=1

print(matriz)

14. Crear una matriz de 5x5 con valores en los renglones que vayan de 0 a 4(investigar)

In [ ]:
matriz=np.tile(np.arange(5),(5,1))
print(matriz)

15. Crear dos arreglos al azar(valores aleatorios) A y B, verificar si son iguales

In [45]:
a=np.random.rand(10)
b=np.random.rand(10)

iguales = np.array_equal(a,b)

print(iguales)

False


16. Crear una matrices 10x10 mostrar las siguiente:
> * mostrar las filas 5 en adelante
> * mostrar solo las tres primeras filas
> * mostrar solo las filas 3 a la 7 

17. Crear una matrices 10x10 con valores aleatorios enteros y calcular la suma de valores siguiente:
> * Calcular la suma de todos valores que sean mayores a 25
> * Calcular la suma de los valores por filas que sean mayores a 10 y menores a 25
> * Calcular la suma de los valores por columnas que sean mayores a 50 y menores a 75