## CLASE DE APUNTES

In [2]:
import numpy as np
import pandas as ps

In [ ]:
np.random.randint(10,100,50)

In [ ]:
np.random.randint(10,100,(5,5))

In [2]:
arr=np.arange(0,11)
print(arr)
arr2=arr[3:8]
print(arr2)
arr2[:]=88
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]
[3 4 5 6 7]
[ 0  1  2 88 88 88 88 88  8  9 10]


In [4]:
arr2=arr.copy()[3:8]
print(arr)
print(arr2)

[ 0  1  2 88 88 88 88 88  8  9 10]
[88 88 88 88 88]


In [11]:
matrix=np.random.randint(1,30,(4,4))
print(matrix)

print(matrix[0,0]) #para el primer

#print(matrix[0])

#retornar las filas 1 y 2

#print(matrix[1:2])

print(matrix[1:]) #suprimir filas.

print(matrix[-1:]) #devuelve las 2 ultimas filas

print(matrix[:-2]) #solo las 2primeras filas


[[28 13 15 28]
 [ 9  9  9 17]
 [27 23 13  6]
 [12 25  3 25]]
28
[[ 9  9  9 17]
 [27 23 13  6]
 [12 25  3 25]]
[[12 25  3 25]]
[[28 13 15 28]
 [ 9  9  9 17]]


In [17]:
arra=np.arange(1,11)
print(arra*5)
print(arra/5)
print(arra+arra)

[ 5 10 15 20 25 30 35 40 45 50]
[0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2. ]
[ 2  4  6  8 10 12 14 16 18 20]


In [22]:
matriz=np.arange(25).reshape(5,5)
print(matriz)

print(matriz.sum(axis=1)) #para columnas es 0 y filas 1

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[ 10  35  60  85 110]


In [24]:
por=np.arange(0,10)

print(por[por>5])

[6 7 8 9]
